/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var include_support_pb = require('./include/support_pb.js');
goog.object.extend(proto, include_support_pb);
var include_page_pb = require('./include/page_pb.js');
goog.object.extend(proto, include_page_pb);
var include_feed_pb = require('./include/feed_pb.js');
goog.object.extend(proto, include_feed_pb);
var include_user_pb = require('./include/user_pb.js');
goog.object.extend(proto, include_user_pb);
goog.exportSymbol('proto.Api_request_wrapper', null, global);
goog.exportSymbol('proto.Api_response_wrapper', null, global);
goog.exportSymbol('proto.Api_response_wrapper.Broad_error_type', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Api_request_wrapper = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.Api_request_wrapper.oneofGroups_);
};
goog.inherits(proto.Api_request_wrapper, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Api_request_wrapper.displayName = 'proto.Api_request_wrapper';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Api_response_wrapper = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.Api_response_wrapper.oneofGroups_);
};
goog.inherits(proto.Api_response_wrapper, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Api_response_wrapper.displayName = 'proto.Api_response_wrapper';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.Api_request_wrapper.oneofGroups_ = [[11,12,13,21,22,31,32,33,34,35]];

/**
 * @enum {number}
 */
proto.Api_request_wrapper.ActualMessageCase = {
  ACTUAL_MESSAGE_NOT_SET: 0,
  PAGE_RENDERING_ELEMENTS: 11,
  PAGE_METADATA: 12,
  CREATE_PAGE: 13,
  FEED_RENDERING_ELEMENTS: 21,
  FEED_METADATA: 22,
  SIGN_IN_PWD_NAIVE: 31,
  SIGN_IN_PWD_POW_1: 32,
  SIGN_IN_HMAC_TOTP: 33,
  SIGN_IN_MAIL_OTP_0: 34,
  SIGN_IN_MAIL_OTP_1: 35
};

/**
 * @return {proto.Api_request_wrapper.ActualMessageCase}
 */
proto.Api_request_wrapper.prototype.getActualMessageCase = function() {
  return /** @type {proto.Api_request_wrapper.ActualMessageCase} */(jspb.Message.computeOneofCase(this, proto.Api_request_wrapper.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Api_request_wrapper.prototype.toObject = function(opt_includeInstance) {
  return proto.Api_request_wrapper.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Api_request_wrapper} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Api_request_wrapper.toObject = function(includeInstance, msg) {
  var f, obj = {
    credential: (f = msg.getCredential()) && include_support_pb.Credential.toObject(includeInstance, f),
    pageRenderingElements: (f = msg.getPageRenderingElements()) && include_page_pb.Request_page_rendering_elements_by_name.toObject(includeInstance, f),
    pageMetadata: (f = msg.getPageMetadata()) && include_page_pb.Request_page_metadata_by_name.toObject(includeInstance, f),
    createPage: (f = msg.getCreatePage()) && include_page_pb.Request_create_page.toObject(includeInstance, f),
    feedRenderingElements: (f = msg.getFeedRenderingElements()) && include_feed_pb.Request_feed_rendering_elements_by_name.toObject(includeInstance, f),
    feedMetadata: (f = msg.getFeedMetadata()) && include_feed_pb.Request_feed_metadata_by_name.toObject(includeInstance, f),
    signInPwdNaive: (f = msg.getSignInPwdNaive()) && include_user_pb.Obtain_credential_by_password_naive_attempt.toObject(includeInstance, f),
    signInPwdPow1: (f = msg.getSignInPwdPow1()) && include_user_pb.Obtain_credential_by_password_pow_1.toObject(includeInstance, f),
    signInHmacTotp: (f = msg.getSignInHmacTotp()) && include_user_pb.Obtain_credential_2fa_hmac_totp_code.toObject(includeInstance, f),
    signInMailOtp0: (f = msg.getSignInMailOtp0()) && include_user_pb.Obtain_credential_mail_otp_step_0_response.toObject(includeInstance, f),
    signInMailOtp1: (f = msg.getSignInMailOtp1()) && include_user_pb.Obtain_credential_mail_otp_step_1_response.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Api_request_wrapper}
 */
proto.Api_request_wrapper.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Api_request_wrapper;
  return proto.Api_request_wrapper.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Api_request_wrapper} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Api_request_wrapper}
 */
proto.Api_request_wrapper.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new include_support_pb.Credential;
      reader.readMessage(value,include_support_pb.Credential.deserializeBinaryFromReader);
      msg.setCredential(value);
      break;
    case 11:
      var value = new include_page_pb.Request_page_rendering_elements_by_name;
      reader.readMessage(value,include_page_pb.Request_page_rendering_elements_by_name.deserializeBinaryFromReader);
      msg.setPageRenderingElements(value);
      break;
    case 12:
      var value = new include_page_pb.Request_page_metadata_by_name;
      reader.readMessage(value,include_page_pb.Request_page_metadata_by_name.deserializeBinaryFromReader);
      msg.setPageMetadata(value);
      break;
    case 13:
      var value = new include_page_pb.Request_create_page;
      reader.readMessage(value,include_page_pb.Request_create_page.deserializeBinaryFromReader);
      msg.setCreatePage(value);
      break;
    case 21:
      var value = new include_feed_pb.Request_feed_rendering_elements_by_name;
      reader.readMessage(value,include_feed_pb.Request_feed_rendering_elements_by_name.deserializeBinaryFromReader);
      msg.setFeedRenderingElements(value);
      break;
    case 22:
      var value = new include_feed_pb.Request_feed_metadata_by_name;
      reader.readMessage(value,include_feed_pb.Request_feed_metadata_by_name.deserializeBinaryFromReader);
      msg.setFeedMetadata(value);
      break;
    case 31:
      var value = new include_user_pb.Obtain_credential_by_password_naive_attempt;
      reader.readMessage(value,include_user_pb.Obtain_credential_by_password_naive_attempt.deserializeBinaryFromReader);
      msg.setSignInPwdNaive(value);
      break;
    case 32:
      var value = new include_user_pb.Obtain_credential_by_password_pow_1;
      reader.readMessage(value,include_user_pb.Obtain_credential_by_password_pow_1.deserializeBinaryFromReader);
      msg.setSignInPwdPow1(value);
      break;
    case 33:
      var value = new include_user_pb.Obtain_credential_2fa_hmac_totp_code;
      reader.readMessage(value,include_user_pb.Obtain_credential_2fa_hmac_totp_code.deserializeBinaryFromReader);
      msg.setSignInHmacTotp(value);
      break;
    case 34:
      var value = new include_user_pb.Obtain_credential_mail_otp_step_0_response;
      reader.readMessage(value,include_user_pb.Obtain_credential_mail_otp_step_0_response.deserializeBinaryFromReader);
      msg.setSignInMailOtp0(value);
      break;
    case 35:
      var value = new include_user_pb.Obtain_credential_mail_otp_step_1_response;
      reader.readMessage(value,include_user_pb.Obtain_credential_mail_otp_step_1_response.deserializeBinaryFromReader);
      msg.setSignInMailOtp1(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Api_request_wrapper.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Api_request_wrapper.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Api_request_wrapper} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Api_request_wrapper.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCredential();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      include_support_pb.Credential.serializeBinaryToWriter
    );
  }
  f = message.getPageRenderingElements();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      include_page_pb.Request_page_rendering_elements_by_name.serializeBinaryToWriter
    );
  }
  f = message.getPageMetadata();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      include_page_pb.Request_page_metadata_by_name.serializeBinaryToWriter
    );
  }
  f = message.getCreatePage();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      include_page_pb.Request_create_page.serializeBinaryToWriter
    );
  }
  f = message.getFeedRenderingElements();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      include_feed_pb.Request_feed_rendering_elements_by_name.serializeBinaryToWriter
    );
  }
  f = message.getFeedMetadata();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      include_feed_pb.Request_feed_metadata_by_name.serializeBinaryToWriter
    );
  }
  f = message.getSignInPwdNaive();
  if (f != null) {
    writer.writeMessage(
      31,
      f,
      include_user_pb.Obtain_credential_by_password_naive_attempt.serializeBinaryToWriter
    );
  }
  f = message.getSignInPwdPow1();
  if (f != null) {
    writer.writeMessage(
      32,
      f,
      include_user_pb.Obtain_credential_by_password_pow_1.serializeBinaryToWriter
    );
  }
  f = message.getSignInHmacTotp();
  if (f != null) {
    writer.writeMessage(
      33,
      f,
      include_user_pb.Obtain_credential_2fa_hmac_totp_code.serializeBinaryToWriter
    );
  }
  f = message.getSignInMailOtp0();
  if (f != null) {
    writer.writeMessage(
      34,
      f,
      include_user_pb.Obtain_credential_mail_otp_step_0_response.serializeBinaryToWriter
    );
  }
  f = message.getSignInMailOtp1();
  if (f != null) {
    writer.writeMessage(
      35,
      f,
      include_user_pb.Obtain_credential_mail_otp_step_1_response.serializeBinaryToWriter
    );
  }
};


/**
 * optional apiv4.support.Credential credential = 1;
 * @return {?proto.apiv4.support.Credential}
 */
proto.Api_request_wrapper.prototype.getCredential = function() {
  return /** @type{?proto.apiv4.support.Credential} */ (
    jspb.Message.getWrapperField(this, include_support_pb.Credential, 1));
};


/** @param {?proto.apiv4.support.Credential|undefined} value */
proto.Api_request_wrapper.prototype.setCredential = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_request_wrapper.prototype.clearCredential = function() {
  this.setCredential(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_request_wrapper.prototype.hasCredential = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional apiv4.page.Request_page_rendering_elements_by_name page_rendering_elements = 11;
 * @return {?proto.apiv4.page.Request_page_rendering_elements_by_name}
 */
proto.Api_request_wrapper.prototype.getPageRenderingElements = function() {
  return /** @type{?proto.apiv4.page.Request_page_rendering_elements_by_name} */ (
    jspb.Message.getWrapperField(this, include_page_pb.Request_page_rendering_elements_by_name, 11));
};


/** @param {?proto.apiv4.page.Request_page_rendering_elements_by_name|undefined} value */
proto.Api_request_wrapper.prototype.setPageRenderingElements = function(value) {
  jspb.Message.setOneofWrapperField(this, 11, proto.Api_request_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_request_wrapper.prototype.clearPageRenderingElements = function() {
  this.setPageRenderingElements(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_request_wrapper.prototype.hasPageRenderingElements = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional apiv4.page.Request_page_metadata_by_name page_metadata = 12;
 * @return {?proto.apiv4.page.Request_page_metadata_by_name}
 */
proto.Api_request_wrapper.prototype.getPageMetadata = function() {
  return /** @type{?proto.apiv4.page.Request_page_metadata_by_name} */ (
    jspb.Message.getWrapperField(this, include_page_pb.Request_page_metadata_by_name, 12));
};


/** @param {?proto.apiv4.page.Request_page_metadata_by_name|undefined} value */
proto.Api_request_wrapper.prototype.setPageMetadata = function(value) {
  jspb.Message.setOneofWrapperField(this, 12, proto.Api_request_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_request_wrapper.prototype.clearPageMetadata = function() {
  this.setPageMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_request_wrapper.prototype.hasPageMetadata = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional apiv4.page.Request_create_page create_page = 13;
 * @return {?proto.apiv4.page.Request_create_page}
 */
proto.Api_request_wrapper.prototype.getCreatePage = function() {
  return /** @type{?proto.apiv4.page.Request_create_page} */ (
    jspb.Message.getWrapperField(this, include_page_pb.Request_create_page, 13));
};


/** @param {?proto.apiv4.page.Request_create_page|undefined} value */
proto.Api_request_wrapper.prototype.setCreatePage = function(value) {
  jspb.Message.setOneofWrapperField(this, 13, proto.Api_request_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_request_wrapper.prototype.clearCreatePage = function() {
  this.setCreatePage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_request_wrapper.prototype.hasCreatePage = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional apiv4.feed.Request_feed_rendering_elements_by_name feed_rendering_elements = 21;
 * @return {?proto.apiv4.feed.Request_feed_rendering_elements_by_name}
 */
proto.Api_request_wrapper.prototype.getFeedRenderingElements = function() {
  return /** @type{?proto.apiv4.feed.Request_feed_rendering_elements_by_name} */ (
    jspb.Message.getWrapperField(this, include_feed_pb.Request_feed_rendering_elements_by_name, 21));
};


/** @param {?proto.apiv4.feed.Request_feed_rendering_elements_by_name|undefined} value */
proto.Api_request_wrapper.prototype.setFeedRenderingElements = function(value) {
  jspb.Message.setOneofWrapperField(this, 21, proto.Api_request_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_request_wrapper.prototype.clearFeedRenderingElements = function() {
  this.setFeedRenderingElements(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_request_wrapper.prototype.hasFeedRenderingElements = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional apiv4.feed.Request_feed_metadata_by_name feed_metadata = 22;
 * @return {?proto.apiv4.feed.Request_feed_metadata_by_name}
 */
proto.Api_request_wrapper.prototype.getFeedMetadata = function() {
  return /** @type{?proto.apiv4.feed.Request_feed_metadata_by_name} */ (
    jspb.Message.getWrapperField(this, include_feed_pb.Request_feed_metadata_by_name, 22));
};


/** @param {?proto.apiv4.feed.Request_feed_metadata_by_name|undefined} value */
proto.Api_request_wrapper.prototype.setFeedMetadata = function(value) {
  jspb.Message.setOneofWrapperField(this, 22, proto.Api_request_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_request_wrapper.prototype.clearFeedMetadata = function() {
  this.setFeedMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_request_wrapper.prototype.hasFeedMetadata = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional apiv4.user.Obtain_credential_by_password_naive_attempt sign_in_pwd_naive = 31;
 * @return {?proto.apiv4.user.Obtain_credential_by_password_naive_attempt}
 */
proto.Api_request_wrapper.prototype.getSignInPwdNaive = function() {
  return /** @type{?proto.apiv4.user.Obtain_credential_by_password_naive_attempt} */ (
    jspb.Message.getWrapperField(this, include_user_pb.Obtain_credential_by_password_naive_attempt, 31));
};


/** @param {?proto.apiv4.user.Obtain_credential_by_password_naive_attempt|undefined} value */
proto.Api_request_wrapper.prototype.setSignInPwdNaive = function(value) {
  jspb.Message.setOneofWrapperField(this, 31, proto.Api_request_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_request_wrapper.prototype.clearSignInPwdNaive = function() {
  this.setSignInPwdNaive(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_request_wrapper.prototype.hasSignInPwdNaive = function() {
  return jspb.Message.getField(this, 31) != null;
};


/**
 * optional apiv4.user.Obtain_credential_by_password_pow_1 sign_in_pwd_pow_1 = 32;
 * @return {?proto.apiv4.user.Obtain_credential_by_password_pow_1}
 */
proto.Api_request_wrapper.prototype.getSignInPwdPow1 = function() {
  return /** @type{?proto.apiv4.user.Obtain_credential_by_password_pow_1} */ (
    jspb.Message.getWrapperField(this, include_user_pb.Obtain_credential_by_password_pow_1, 32));
};


/** @param {?proto.apiv4.user.Obtain_credential_by_password_pow_1|undefined} value */
proto.Api_request_wrapper.prototype.setSignInPwdPow1 = function(value) {
  jspb.Message.setOneofWrapperField(this, 32, proto.Api_request_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_request_wrapper.prototype.clearSignInPwdPow1 = function() {
  this.setSignInPwdPow1(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_request_wrapper.prototype.hasSignInPwdPow1 = function() {
  return jspb.Message.getField(this, 32) != null;
};


/**
 * optional apiv4.user.Obtain_credential_2fa_hmac_totp_code sign_in_hmac_totp = 33;
 * @return {?proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code}
 */
proto.Api_request_wrapper.prototype.getSignInHmacTotp = function() {
  return /** @type{?proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code} */ (
    jspb.Message.getWrapperField(this, include_user_pb.Obtain_credential_2fa_hmac_totp_code, 33));
};


/** @param {?proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code|undefined} value */
proto.Api_request_wrapper.prototype.setSignInHmacTotp = function(value) {
  jspb.Message.setOneofWrapperField(this, 33, proto.Api_request_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_request_wrapper.prototype.clearSignInHmacTotp = function() {
  this.setSignInHmacTotp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_request_wrapper.prototype.hasSignInHmacTotp = function() {
  return jspb.Message.getField(this, 33) != null;
};


/**
 * optional apiv4.user.Obtain_credential_mail_otp_step_0_response sign_in_mail_otp_0 = 34;
 * @return {?proto.apiv4.user.Obtain_credential_mail_otp_step_0_response}
 */
proto.Api_request_wrapper.prototype.getSignInMailOtp0 = function() {
  return /** @type{?proto.apiv4.user.Obtain_credential_mail_otp_step_0_response} */ (
    jspb.Message.getWrapperField(this, include_user_pb.Obtain_credential_mail_otp_step_0_response, 34));
};


/** @param {?proto.apiv4.user.Obtain_credential_mail_otp_step_0_response|undefined} value */
proto.Api_request_wrapper.prototype.setSignInMailOtp0 = function(value) {
  jspb.Message.setOneofWrapperField(this, 34, proto.Api_request_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_request_wrapper.prototype.clearSignInMailOtp0 = function() {
  this.setSignInMailOtp0(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_request_wrapper.prototype.hasSignInMailOtp0 = function() {
  return jspb.Message.getField(this, 34) != null;
};


/**
 * optional apiv4.user.Obtain_credential_mail_otp_step_1_response sign_in_mail_otp_1 = 35;
 * @return {?proto.apiv4.user.Obtain_credential_mail_otp_step_1_response}
 */
proto.Api_request_wrapper.prototype.getSignInMailOtp1 = function() {
  return /** @type{?proto.apiv4.user.Obtain_credential_mail_otp_step_1_response} */ (
    jspb.Message.getWrapperField(this, include_user_pb.Obtain_credential_mail_otp_step_1_response, 35));
};


/** @param {?proto.apiv4.user.Obtain_credential_mail_otp_step_1_response|undefined} value */
proto.Api_request_wrapper.prototype.setSignInMailOtp1 = function(value) {
  jspb.Message.setOneofWrapperField(this, 35, proto.Api_request_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_request_wrapper.prototype.clearSignInMailOtp1 = function() {
  this.setSignInMailOtp1(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_request_wrapper.prototype.hasSignInMailOtp1 = function() {
  return jspb.Message.getField(this, 35) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.Api_response_wrapper.oneofGroups_ = [[11,12,21,22,31,41,42,43,44]];

/**
 * @enum {number}
 */
proto.Api_response_wrapper.ActualMessageCase = {
  ACTUAL_MESSAGE_NOT_SET: 0,
  PAGE_RENDERING_ELEMENTS: 11,
  PAGE_METADATA: 12,
  FEED_RENDERING_ELEMENTS: 21,
  FEED_METADATA: 22,
  POW_REQUIRED: 31,
  SIGN_IN_HMAC_TOTP_REQUIRED: 41,
  SIGN_IN_MAIL_TOTP_STEP_0: 42,
  SIGN_IN_MAIL_TOTP_STEP_1: 43,
  CREDENTIAL_GRANTED: 44
};

/**
 * @return {proto.Api_response_wrapper.ActualMessageCase}
 */
proto.Api_response_wrapper.prototype.getActualMessageCase = function() {
  return /** @type {proto.Api_response_wrapper.ActualMessageCase} */(jspb.Message.computeOneofCase(this, proto.Api_response_wrapper.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Api_response_wrapper.prototype.toObject = function(opt_includeInstance) {
  return proto.Api_response_wrapper.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Api_response_wrapper} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Api_response_wrapper.toObject = function(includeInstance, msg) {
  var f, obj = {
    executionOk: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    error: jspb.Message.getFieldWithDefault(msg, 2, 0),
    pageRenderingElements: (f = msg.getPageRenderingElements()) && include_page_pb.Page_with_rendering_elements.toObject(includeInstance, f),
    pageMetadata: (f = msg.getPageMetadata()) && include_page_pb.Page_metadata.toObject(includeInstance, f),
    feedRenderingElements: (f = msg.getFeedRenderingElements()) && include_feed_pb.Feed_with_rendering_elements.toObject(includeInstance, f),
    feedMetadata: (f = msg.getFeedMetadata()) && include_feed_pb.Feed_metadata.toObject(includeInstance, f),
    powRequired: (f = msg.getPowRequired()) && include_support_pb.Proof_of_work_required_to_continue.toObject(includeInstance, f),
    signInHmacTotpRequired: (f = msg.getSignInHmacTotpRequired()) && include_user_pb.Reply_2fa_hmac_totp_required_to_obtain_credential.toObject(includeInstance, f),
    signInMailTotpStep0: (f = msg.getSignInMailTotpStep0()) && include_user_pb.Reply_2fa_mail_otp_step_0_verify_email_addr.toObject(includeInstance, f),
    signInMailTotpStep1: (f = msg.getSignInMailTotpStep1()) && include_user_pb.Reply_2fa_mail_otp_step_1_mail_sent.toObject(includeInstance, f),
    credentialGranted: (f = msg.getCredentialGranted()) && include_user_pb.Response_credential_granted.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Api_response_wrapper}
 */
proto.Api_response_wrapper.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Api_response_wrapper;
  return proto.Api_response_wrapper.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Api_response_wrapper} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Api_response_wrapper}
 */
proto.Api_response_wrapper.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setExecutionOk(value);
      break;
    case 2:
      var value = /** @type {!proto.Api_response_wrapper.Broad_error_type} */ (reader.readEnum());
      msg.setError(value);
      break;
    case 11:
      var value = new include_page_pb.Page_with_rendering_elements;
      reader.readMessage(value,include_page_pb.Page_with_rendering_elements.deserializeBinaryFromReader);
      msg.setPageRenderingElements(value);
      break;
    case 12:
      var value = new include_page_pb.Page_metadata;
      reader.readMessage(value,include_page_pb.Page_metadata.deserializeBinaryFromReader);
      msg.setPageMetadata(value);
      break;
    case 21:
      var value = new include_feed_pb.Feed_with_rendering_elements;
      reader.readMessage(value,include_feed_pb.Feed_with_rendering_elements.deserializeBinaryFromReader);
      msg.setFeedRenderingElements(value);
      break;
    case 22:
      var value = new include_feed_pb.Feed_metadata;
      reader.readMessage(value,include_feed_pb.Feed_metadata.deserializeBinaryFromReader);
      msg.setFeedMetadata(value);
      break;
    case 31:
      var value = new include_support_pb.Proof_of_work_required_to_continue;
      reader.readMessage(value,include_support_pb.Proof_of_work_required_to_continue.deserializeBinaryFromReader);
      msg.setPowRequired(value);
      break;
    case 41:
      var value = new include_user_pb.Reply_2fa_hmac_totp_required_to_obtain_credential;
      reader.readMessage(value,include_user_pb.Reply_2fa_hmac_totp_required_to_obtain_credential.deserializeBinaryFromReader);
      msg.setSignInHmacTotpRequired(value);
      break;
    case 42:
      var value = new include_user_pb.Reply_2fa_mail_otp_step_0_verify_email_addr;
      reader.readMessage(value,include_user_pb.Reply_2fa_mail_otp_step_0_verify_email_addr.deserializeBinaryFromReader);
      msg.setSignInMailTotpStep0(value);
      break;
    case 43:
      var value = new include_user_pb.Reply_2fa_mail_otp_step_1_mail_sent;
      reader.readMessage(value,include_user_pb.Reply_2fa_mail_otp_step_1_mail_sent.deserializeBinaryFromReader);
      msg.setSignInMailTotpStep1(value);
      break;
    case 44:
      var value = new include_user_pb.Response_credential_granted;
      reader.readMessage(value,include_user_pb.Response_credential_granted.deserializeBinaryFromReader);
      msg.setCredentialGranted(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Api_response_wrapper.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Api_response_wrapper.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Api_response_wrapper} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Api_response_wrapper.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getExecutionOk();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getError();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getPageRenderingElements();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      include_page_pb.Page_with_rendering_elements.serializeBinaryToWriter
    );
  }
  f = message.getPageMetadata();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      include_page_pb.Page_metadata.serializeBinaryToWriter
    );
  }
  f = message.getFeedRenderingElements();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      include_feed_pb.Feed_with_rendering_elements.serializeBinaryToWriter
    );
  }
  f = message.getFeedMetadata();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      include_feed_pb.Feed_metadata.serializeBinaryToWriter
    );
  }
  f = message.getPowRequired();
  if (f != null) {
    writer.writeMessage(
      31,
      f,
      include_support_pb.Proof_of_work_required_to_continue.serializeBinaryToWriter
    );
  }
  f = message.getSignInHmacTotpRequired();
  if (f != null) {
    writer.writeMessage(
      41,
      f,
      include_user_pb.Reply_2fa_hmac_totp_required_to_obtain_credential.serializeBinaryToWriter
    );
  }
  f = message.getSignInMailTotpStep0();
  if (f != null) {
    writer.writeMessage(
      42,
      f,
      include_user_pb.Reply_2fa_mail_otp_step_0_verify_email_addr.serializeBinaryToWriter
    );
  }
  f = message.getSignInMailTotpStep1();
  if (f != null) {
    writer.writeMessage(
      43,
      f,
      include_user_pb.Reply_2fa_mail_otp_step_1_mail_sent.serializeBinaryToWriter
    );
  }
  f = message.getCredentialGranted();
  if (f != null) {
    writer.writeMessage(
      44,
      f,
      include_user_pb.Response_credential_granted.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.Api_response_wrapper.Broad_error_type = {
  NO_INFO: 0,
  INSUFFICIENT_PERMISSION: 1,
  INVALID_MESSAGE: 2,
  DNE: 3,
  MISSION_SPECIFIC: 4
};

/**
 * optional bool execution_ok = 1;
 * @return {boolean}
 */
proto.Api_response_wrapper.prototype.getExecutionOk = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.Api_response_wrapper.prototype.setExecutionOk = function(value) {
  jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional Broad_error_type error = 2;
 * @return {!proto.Api_response_wrapper.Broad_error_type}
 */
proto.Api_response_wrapper.prototype.getError = function() {
  return /** @type {!proto.Api_response_wrapper.Broad_error_type} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.Api_response_wrapper.Broad_error_type} value */
proto.Api_response_wrapper.prototype.setError = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional apiv4.page.Page_with_rendering_elements page_rendering_elements = 11;
 * @return {?proto.apiv4.page.Page_with_rendering_elements}
 */
proto.Api_response_wrapper.prototype.getPageRenderingElements = function() {
  return /** @type{?proto.apiv4.page.Page_with_rendering_elements} */ (
    jspb.Message.getWrapperField(this, include_page_pb.Page_with_rendering_elements, 11));
};


/** @param {?proto.apiv4.page.Page_with_rendering_elements|undefined} value */
proto.Api_response_wrapper.prototype.setPageRenderingElements = function(value) {
  jspb.Message.setOneofWrapperField(this, 11, proto.Api_response_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_response_wrapper.prototype.clearPageRenderingElements = function() {
  this.setPageRenderingElements(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_response_wrapper.prototype.hasPageRenderingElements = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional apiv4.page.Page_metadata page_metadata = 12;
 * @return {?proto.apiv4.page.Page_metadata}
 */
proto.Api_response_wrapper.prototype.getPageMetadata = function() {
  return /** @type{?proto.apiv4.page.Page_metadata} */ (
    jspb.Message.getWrapperField(this, include_page_pb.Page_metadata, 12));
};


/** @param {?proto.apiv4.page.Page_metadata|undefined} value */
proto.Api_response_wrapper.prototype.setPageMetadata = function(value) {
  jspb.Message.setOneofWrapperField(this, 12, proto.Api_response_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_response_wrapper.prototype.clearPageMetadata = function() {
  this.setPageMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_response_wrapper.prototype.hasPageMetadata = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional apiv4.feed.Feed_with_rendering_elements feed_rendering_elements = 21;
 * @return {?proto.apiv4.feed.Feed_with_rendering_elements}
 */
proto.Api_response_wrapper.prototype.getFeedRenderingElements = function() {
  return /** @type{?proto.apiv4.feed.Feed_with_rendering_elements} */ (
    jspb.Message.getWrapperField(this, include_feed_pb.Feed_with_rendering_elements, 21));
};


/** @param {?proto.apiv4.feed.Feed_with_rendering_elements|undefined} value */
proto.Api_response_wrapper.prototype.setFeedRenderingElements = function(value) {
  jspb.Message.setOneofWrapperField(this, 21, proto.Api_response_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_response_wrapper.prototype.clearFeedRenderingElements = function() {
  this.setFeedRenderingElements(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_response_wrapper.prototype.hasFeedRenderingElements = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional apiv4.feed.Feed_metadata feed_metadata = 22;
 * @return {?proto.apiv4.feed.Feed_metadata}
 */
proto.Api_response_wrapper.prototype.getFeedMetadata = function() {
  return /** @type{?proto.apiv4.feed.Feed_metadata} */ (
    jspb.Message.getWrapperField(this, include_feed_pb.Feed_metadata, 22));
};


/** @param {?proto.apiv4.feed.Feed_metadata|undefined} value */
proto.Api_response_wrapper.prototype.setFeedMetadata = function(value) {
  jspb.Message.setOneofWrapperField(this, 22, proto.Api_response_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_response_wrapper.prototype.clearFeedMetadata = function() {
  this.setFeedMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_response_wrapper.prototype.hasFeedMetadata = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional apiv4.support.Proof_of_work_required_to_continue pow_required = 31;
 * @return {?proto.apiv4.support.Proof_of_work_required_to_continue}
 */
proto.Api_response_wrapper.prototype.getPowRequired = function() {
  return /** @type{?proto.apiv4.support.Proof_of_work_required_to_continue} */ (
    jspb.Message.getWrapperField(this, include_support_pb.Proof_of_work_required_to_continue, 31));
};


/** @param {?proto.apiv4.support.Proof_of_work_required_to_continue|undefined} value */
proto.Api_response_wrapper.prototype.setPowRequired = function(value) {
  jspb.Message.setOneofWrapperField(this, 31, proto.Api_response_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_response_wrapper.prototype.clearPowRequired = function() {
  this.setPowRequired(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_response_wrapper.prototype.hasPowRequired = function() {
  return jspb.Message.getField(this, 31) != null;
};


/**
 * optional apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential sign_in_hmac_totp_required = 41;
 * @return {?proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential}
 */
proto.Api_response_wrapper.prototype.getSignInHmacTotpRequired = function() {
  return /** @type{?proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential} */ (
    jspb.Message.getWrapperField(this, include_user_pb.Reply_2fa_hmac_totp_required_to_obtain_credential, 41));
};


/** @param {?proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential|undefined} value */
proto.Api_response_wrapper.prototype.setSignInHmacTotpRequired = function(value) {
  jspb.Message.setOneofWrapperField(this, 41, proto.Api_response_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_response_wrapper.prototype.clearSignInHmacTotpRequired = function() {
  this.setSignInHmacTotpRequired(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_response_wrapper.prototype.hasSignInHmacTotpRequired = function() {
  return jspb.Message.getField(this, 41) != null;
};


/**
 * optional apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr sign_in_mail_totp_step_0 = 42;
 * @return {?proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr}
 */
proto.Api_response_wrapper.prototype.getSignInMailTotpStep0 = function() {
  return /** @type{?proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr} */ (
    jspb.Message.getWrapperField(this, include_user_pb.Reply_2fa_mail_otp_step_0_verify_email_addr, 42));
};


/** @param {?proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr|undefined} value */
proto.Api_response_wrapper.prototype.setSignInMailTotpStep0 = function(value) {
  jspb.Message.setOneofWrapperField(this, 42, proto.Api_response_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_response_wrapper.prototype.clearSignInMailTotpStep0 = function() {
  this.setSignInMailTotpStep0(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_response_wrapper.prototype.hasSignInMailTotpStep0 = function() {
  return jspb.Message.getField(this, 42) != null;
};


/**
 * optional apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent sign_in_mail_totp_step_1 = 43;
 * @return {?proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent}
 */
proto.Api_response_wrapper.prototype.getSignInMailTotpStep1 = function() {
  return /** @type{?proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent} */ (
    jspb.Message.getWrapperField(this, include_user_pb.Reply_2fa_mail_otp_step_1_mail_sent, 43));
};


/** @param {?proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent|undefined} value */
proto.Api_response_wrapper.prototype.setSignInMailTotpStep1 = function(value) {
  jspb.Message.setOneofWrapperField(this, 43, proto.Api_response_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_response_wrapper.prototype.clearSignInMailTotpStep1 = function() {
  this.setSignInMailTotpStep1(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_response_wrapper.prototype.hasSignInMailTotpStep1 = function() {
  return jspb.Message.getField(this, 43) != null;
};


/**
 * optional apiv4.user.Response_credential_granted credential_granted = 44;
 * @return {?proto.apiv4.user.Response_credential_granted}
 */
proto.Api_response_wrapper.prototype.getCredentialGranted = function() {
  return /** @type{?proto.apiv4.user.Response_credential_granted} */ (
    jspb.Message.getWrapperField(this, include_user_pb.Response_credential_granted, 44));
};


/** @param {?proto.apiv4.user.Response_credential_granted|undefined} value */
proto.Api_response_wrapper.prototype.setCredentialGranted = function(value) {
  jspb.Message.setOneofWrapperField(this, 44, proto.Api_response_wrapper.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Api_response_wrapper.prototype.clearCredentialGranted = function() {
  this.setCredentialGranted(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Api_response_wrapper.prototype.hasCredentialGranted = function() {
  return jspb.Message.getField(this, 44) != null;
};


goog.object.extend(exports, proto);
