/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var include_revision_pb = require('../include/revision_pb.js');
goog.object.extend(proto, include_revision_pb);
var include_user_pb = require('../include/user_pb.js');
goog.object.extend(proto, include_user_pb);
goog.exportSymbol('proto.apiv4.page.Page_creation_report', null, global);
goog.exportSymbol('proto.apiv4.page.Page_metadata', null, global);
goog.exportSymbol('proto.apiv4.page.Page_with_rendering_elements', null, global);
goog.exportSymbol('proto.apiv4.page.Request_create_or_edit_page', null, global);
goog.exportSymbol('proto.apiv4.page.Request_create_or_edit_page.Visibility', null, global);
goog.exportSymbol('proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns', null, global);
goog.exportSymbol('proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.Direction', null, global);
goog.exportSymbol('proto.apiv4.page.Request_page_metadata_by_name', null, global);
goog.exportSymbol('proto.apiv4.page.Request_page_rendering_elements_by_name', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.page.Page_metadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apiv4.page.Page_metadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.page.Page_metadata.displayName = 'proto.apiv4.page.Page_metadata';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.page.Page_with_rendering_elements = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apiv4.page.Page_with_rendering_elements, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.page.Page_with_rendering_elements.displayName = 'proto.apiv4.page.Page_with_rendering_elements';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.page.Request_page_rendering_elements_by_name = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apiv4.page.Request_page_rendering_elements_by_name, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.page.Request_page_rendering_elements_by_name.displayName = 'proto.apiv4.page.Request_page_rendering_elements_by_name';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.page.Request_page_metadata_by_name = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apiv4.page.Request_page_metadata_by_name, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.page.Request_page_metadata_by_name.displayName = 'proto.apiv4.page.Request_page_metadata_by_name';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.page.Request_create_or_edit_page = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apiv4.page.Request_create_or_edit_page, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.page.Request_create_or_edit_page.displayName = 'proto.apiv4.page.Request_create_or_edit_page';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.oneofGroups_);
};
goog.inherits(proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.displayName = 'proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.page.Page_creation_report = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apiv4.page.Page_creation_report, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.page.Page_creation_report.displayName = 'proto.apiv4.page.Page_creation_report';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.page.Page_metadata.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.page.Page_metadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.page.Page_metadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.page.Page_metadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    pageName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    namespace: jspb.Message.getFieldWithDefault(msg, 2, ""),
    languageCode: jspb.Message.getFieldWithDefault(msg, 3, ""),
    pageIdBis: jspb.Message.getFieldWithDefault(msg, 4, ""),
    creationTimeIso: jspb.Message.getFieldWithDefault(msg, 6, ""),
    updateTimeIso: jspb.Message.getFieldWithDefault(msg, 7, ""),
    viewPermissionIdBis: jspb.Message.getFieldWithDefault(msg, 8, ""),
    licensePageName: jspb.Message.getFieldWithDefault(msg, 9, ""),
    pageContentModel: jspb.Message.getFieldWithDefault(msg, 10, ""),
    eventIdBis: jspb.Message.getFieldWithDefault(msg, 11, ""),
    creatorDisplayName: jspb.Message.getFieldWithDefault(msg, 12, ""),
    creatorIdName: jspb.Message.getFieldWithDefault(msg, 13, ""),
    currentEditorDisplayName: jspb.Message.getFieldWithDefault(msg, 14, ""),
    currentEditorIdName: jspb.Message.getFieldWithDefault(msg, 15, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.page.Page_metadata}
 */
proto.apiv4.page.Page_metadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.page.Page_metadata;
  return proto.apiv4.page.Page_metadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.page.Page_metadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.page.Page_metadata}
 */
proto.apiv4.page.Page_metadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNamespace(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguageCode(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageIdBis(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreationTimeIso(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdateTimeIso(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setViewPermissionIdBis(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setLicensePageName(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageContentModel(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventIdBis(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatorDisplayName(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatorIdName(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrentEditorDisplayName(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrentEditorIdName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.page.Page_metadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.page.Page_metadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.page.Page_metadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.page.Page_metadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPageName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNamespace();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLanguageCode();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPageIdBis();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCreationTimeIso();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getUpdateTimeIso();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getViewPermissionIdBis();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getLicensePageName();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getPageContentModel();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getEventIdBis();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getCreatorDisplayName();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getCreatorIdName();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getCurrentEditorDisplayName();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getCurrentEditorIdName();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
};


/**
 * optional string page_name = 1;
 * @return {string}
 */
proto.apiv4.page.Page_metadata.prototype.getPageName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.apiv4.page.Page_metadata.prototype.setPageName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string namespace = 2;
 * @return {string}
 */
proto.apiv4.page.Page_metadata.prototype.getNamespace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.apiv4.page.Page_metadata.prototype.setNamespace = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string language_code = 3;
 * @return {string}
 */
proto.apiv4.page.Page_metadata.prototype.getLanguageCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.apiv4.page.Page_metadata.prototype.setLanguageCode = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string page_id_bis = 4;
 * @return {string}
 */
proto.apiv4.page.Page_metadata.prototype.getPageIdBis = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.apiv4.page.Page_metadata.prototype.setPageIdBis = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string creation_time_iso = 6;
 * @return {string}
 */
proto.apiv4.page.Page_metadata.prototype.getCreationTimeIso = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.apiv4.page.Page_metadata.prototype.setCreationTimeIso = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string update_time_iso = 7;
 * @return {string}
 */
proto.apiv4.page.Page_metadata.prototype.getUpdateTimeIso = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.apiv4.page.Page_metadata.prototype.setUpdateTimeIso = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string view_permission_id_bis = 8;
 * @return {string}
 */
proto.apiv4.page.Page_metadata.prototype.getViewPermissionIdBis = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.apiv4.page.Page_metadata.prototype.setViewPermissionIdBis = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string license_page_name = 9;
 * @return {string}
 */
proto.apiv4.page.Page_metadata.prototype.getLicensePageName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.apiv4.page.Page_metadata.prototype.setLicensePageName = function(value) {
  jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string page_content_model = 10;
 * @return {string}
 */
proto.apiv4.page.Page_metadata.prototype.getPageContentModel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.apiv4.page.Page_metadata.prototype.setPageContentModel = function(value) {
  jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string event_id_bis = 11;
 * @return {string}
 */
proto.apiv4.page.Page_metadata.prototype.getEventIdBis = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/** @param {string} value */
proto.apiv4.page.Page_metadata.prototype.setEventIdBis = function(value) {
  jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string creator_display_name = 12;
 * @return {string}
 */
proto.apiv4.page.Page_metadata.prototype.getCreatorDisplayName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/** @param {string} value */
proto.apiv4.page.Page_metadata.prototype.setCreatorDisplayName = function(value) {
  jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string creator_id_name = 13;
 * @return {string}
 */
proto.apiv4.page.Page_metadata.prototype.getCreatorIdName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/** @param {string} value */
proto.apiv4.page.Page_metadata.prototype.setCreatorIdName = function(value) {
  jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string current_editor_display_name = 14;
 * @return {string}
 */
proto.apiv4.page.Page_metadata.prototype.getCurrentEditorDisplayName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/** @param {string} value */
proto.apiv4.page.Page_metadata.prototype.setCurrentEditorDisplayName = function(value) {
  jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional string current_editor_id_name = 15;
 * @return {string}
 */
proto.apiv4.page.Page_metadata.prototype.getCurrentEditorIdName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/** @param {string} value */
proto.apiv4.page.Page_metadata.prototype.setCurrentEditorIdName = function(value) {
  jspb.Message.setProto3StringField(this, 15, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.page.Page_with_rendering_elements.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.page.Page_with_rendering_elements.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.page.Page_with_rendering_elements} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.page.Page_with_rendering_elements.toObject = function(includeInstance, msg) {
  var f, obj = {
    pageMeta: (f = msg.getPageMeta()) && proto.apiv4.page.Page_metadata.toObject(includeInstance, f),
    revMeta: (f = msg.getRevMeta()) && include_revision_pb.Revision_metadata.toObject(includeInstance, f),
    content: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.page.Page_with_rendering_elements}
 */
proto.apiv4.page.Page_with_rendering_elements.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.page.Page_with_rendering_elements;
  return proto.apiv4.page.Page_with_rendering_elements.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.page.Page_with_rendering_elements} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.page.Page_with_rendering_elements}
 */
proto.apiv4.page.Page_with_rendering_elements.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.apiv4.page.Page_metadata;
      reader.readMessage(value,proto.apiv4.page.Page_metadata.deserializeBinaryFromReader);
      msg.setPageMeta(value);
      break;
    case 2:
      var value = new include_revision_pb.Revision_metadata;
      reader.readMessage(value,include_revision_pb.Revision_metadata.deserializeBinaryFromReader);
      msg.setRevMeta(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.page.Page_with_rendering_elements.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.page.Page_with_rendering_elements.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.page.Page_with_rendering_elements} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.page.Page_with_rendering_elements.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPageMeta();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.apiv4.page.Page_metadata.serializeBinaryToWriter
    );
  }
  f = message.getRevMeta();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      include_revision_pb.Revision_metadata.serializeBinaryToWriter
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional Page_metadata page_meta = 1;
 * @return {?proto.apiv4.page.Page_metadata}
 */
proto.apiv4.page.Page_with_rendering_elements.prototype.getPageMeta = function() {
  return /** @type{?proto.apiv4.page.Page_metadata} */ (
    jspb.Message.getWrapperField(this, proto.apiv4.page.Page_metadata, 1));
};


/** @param {?proto.apiv4.page.Page_metadata|undefined} value */
proto.apiv4.page.Page_with_rendering_elements.prototype.setPageMeta = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.apiv4.page.Page_with_rendering_elements.prototype.clearPageMeta = function() {
  this.setPageMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apiv4.page.Page_with_rendering_elements.prototype.hasPageMeta = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional apiv4.revision.Revision_metadata rev_meta = 2;
 * @return {?proto.apiv4.revision.Revision_metadata}
 */
proto.apiv4.page.Page_with_rendering_elements.prototype.getRevMeta = function() {
  return /** @type{?proto.apiv4.revision.Revision_metadata} */ (
    jspb.Message.getWrapperField(this, include_revision_pb.Revision_metadata, 2));
};


/** @param {?proto.apiv4.revision.Revision_metadata|undefined} value */
proto.apiv4.page.Page_with_rendering_elements.prototype.setRevMeta = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.apiv4.page.Page_with_rendering_elements.prototype.clearRevMeta = function() {
  this.setRevMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apiv4.page.Page_with_rendering_elements.prototype.hasRevMeta = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string content = 3;
 * @return {string}
 */
proto.apiv4.page.Page_with_rendering_elements.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.apiv4.page.Page_with_rendering_elements.prototype.setContent = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.page.Request_page_rendering_elements_by_name.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.page.Request_page_rendering_elements_by_name.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.page.Request_page_rendering_elements_by_name} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.page.Request_page_rendering_elements_by_name.toObject = function(includeInstance, msg) {
  var f, obj = {
    pageName: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.page.Request_page_rendering_elements_by_name}
 */
proto.apiv4.page.Request_page_rendering_elements_by_name.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.page.Request_page_rendering_elements_by_name;
  return proto.apiv4.page.Request_page_rendering_elements_by_name.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.page.Request_page_rendering_elements_by_name} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.page.Request_page_rendering_elements_by_name}
 */
proto.apiv4.page.Request_page_rendering_elements_by_name.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.page.Request_page_rendering_elements_by_name.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.page.Request_page_rendering_elements_by_name.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.page.Request_page_rendering_elements_by_name} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.page.Request_page_rendering_elements_by_name.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPageName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string page_name = 1;
 * @return {string}
 */
proto.apiv4.page.Request_page_rendering_elements_by_name.prototype.getPageName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.apiv4.page.Request_page_rendering_elements_by_name.prototype.setPageName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.page.Request_page_metadata_by_name.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.page.Request_page_metadata_by_name.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.page.Request_page_metadata_by_name} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.page.Request_page_metadata_by_name.toObject = function(includeInstance, msg) {
  var f, obj = {
    pageName: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.page.Request_page_metadata_by_name}
 */
proto.apiv4.page.Request_page_metadata_by_name.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.page.Request_page_metadata_by_name;
  return proto.apiv4.page.Request_page_metadata_by_name.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.page.Request_page_metadata_by_name} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.page.Request_page_metadata_by_name}
 */
proto.apiv4.page.Request_page_metadata_by_name.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.page.Request_page_metadata_by_name.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.page.Request_page_metadata_by_name.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.page.Request_page_metadata_by_name} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.page.Request_page_metadata_by_name.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPageName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string page_name = 1;
 * @return {string}
 */
proto.apiv4.page.Request_page_metadata_by_name.prototype.getPageName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.apiv4.page.Request_page_metadata_by_name.prototype.setPageName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.page.Request_create_or_edit_page.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.page.Request_create_or_edit_page.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.page.Request_create_or_edit_page} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.page.Request_create_or_edit_page.toObject = function(includeInstance, msg) {
  var f, obj = {
    pageName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    content: jspb.Message.getFieldWithDefault(msg, 3, ""),
    revisionComment: jspb.Message.getFieldWithDefault(msg, 4, ""),
    visibility: jspb.Message.getFieldWithDefault(msg, 5, 0),
    contentType: jspb.Message.getFieldWithDefault(msg, 6, ""),
    languageCode: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.page.Request_create_or_edit_page}
 */
proto.apiv4.page.Request_create_or_edit_page.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.page.Request_create_or_edit_page;
  return proto.apiv4.page.Request_create_or_edit_page.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.page.Request_create_or_edit_page} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.page.Request_create_or_edit_page}
 */
proto.apiv4.page.Request_create_or_edit_page.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRevisionComment(value);
      break;
    case 5:
      var value = /** @type {!proto.apiv4.page.Request_create_or_edit_page.Visibility} */ (reader.readEnum());
      msg.setVisibility(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setContentType(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguageCode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.page.Request_create_or_edit_page.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.page.Request_create_or_edit_page.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.page.Request_create_or_edit_page} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.page.Request_create_or_edit_page.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPageName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRevisionComment();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getVisibility();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getContentType();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getLanguageCode();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.apiv4.page.Request_create_or_edit_page.Visibility = {
  ALL_VISIBLE: 0,
  ADMIN_VISIBLE: 1,
  SELF_VISIBLE: 2
};

/**
 * optional string page_name = 1;
 * @return {string}
 */
proto.apiv4.page.Request_create_or_edit_page.prototype.getPageName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.apiv4.page.Request_create_or_edit_page.prototype.setPageName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string content = 3;
 * @return {string}
 */
proto.apiv4.page.Request_create_or_edit_page.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.apiv4.page.Request_create_or_edit_page.prototype.setContent = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string revision_comment = 4;
 * @return {string}
 */
proto.apiv4.page.Request_create_or_edit_page.prototype.getRevisionComment = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.apiv4.page.Request_create_or_edit_page.prototype.setRevisionComment = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional Visibility visibility = 5;
 * @return {!proto.apiv4.page.Request_create_or_edit_page.Visibility}
 */
proto.apiv4.page.Request_create_or_edit_page.prototype.getVisibility = function() {
  return /** @type {!proto.apiv4.page.Request_create_or_edit_page.Visibility} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {!proto.apiv4.page.Request_create_or_edit_page.Visibility} value */
proto.apiv4.page.Request_create_or_edit_page.prototype.setVisibility = function(value) {
  jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional string content_type = 6;
 * @return {string}
 */
proto.apiv4.page.Request_create_or_edit_page.prototype.getContentType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.apiv4.page.Request_create_or_edit_page.prototype.setContentType = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string language_code = 7;
 * @return {string}
 */
proto.apiv4.page.Request_create_or_edit_page.prototype.getLanguageCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.apiv4.page.Request_create_or_edit_page.prototype.setLanguageCode = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.oneofGroups_ = [[4,5]];

/**
 * @enum {number}
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.StartFromCase = {
  START_FROM_NOT_SET: 0,
  REV_ID_BIS_NONINCLUSIVE: 4,
  TIMESTAMP_ISO_NONINCLUSIVE: 5
};

/**
 * @return {proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.StartFromCase}
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.prototype.getStartFromCase = function() {
  return /** @type {proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.StartFromCase} */(jspb.Message.computeOneofCase(this, proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.toObject = function(includeInstance, msg) {
  var f, obj = {
    pageApparentName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    direction: jspb.Message.getFieldWithDefault(msg, 2, 0),
    startFromMiddle: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    revIdBisNoninclusive: jspb.Message.getFieldWithDefault(msg, 4, ""),
    timestampIsoNoninclusive: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns}
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns;
  return proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns}
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageApparentName(value);
      break;
    case 2:
      var value = /** @type {!proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.Direction} */ (reader.readEnum());
      msg.setDirection(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setStartFromMiddle(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRevIdBisNoninclusive(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTimestampIsoNoninclusive(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPageApparentName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDirection();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getStartFromMiddle();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.Direction = {
  NEW_TO_OLD: 0,
  OLD_TO_NEW: 1
};

/**
 * optional string page_apparent_name = 1;
 * @return {string}
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.prototype.getPageApparentName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.prototype.setPageApparentName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Direction direction = 2;
 * @return {!proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.Direction}
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.prototype.getDirection = function() {
  return /** @type {!proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.Direction} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.Direction} value */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.prototype.setDirection = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional bool start_from_middle = 3;
 * @return {boolean}
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.prototype.getStartFromMiddle = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.prototype.setStartFromMiddle = function(value) {
  jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional string rev_id_bis_noninclusive = 4;
 * @return {string}
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.prototype.getRevIdBisNoninclusive = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.prototype.setRevIdBisNoninclusive = function(value) {
  jspb.Message.setOneofField(this, 4, proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.prototype.clearRevIdBisNoninclusive = function() {
  jspb.Message.setOneofField(this, 4, proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.prototype.hasRevIdBisNoninclusive = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string timestamp_iso_noninclusive = 5;
 * @return {string}
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.prototype.getTimestampIsoNoninclusive = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.prototype.setTimestampIsoNoninclusive = function(value) {
  jspb.Message.setOneofField(this, 5, proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.prototype.clearTimestampIsoNoninclusive = function() {
  jspb.Message.setOneofField(this, 5, proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apiv4.page.Request_history_rendering_elements_by_page_name_ns.prototype.hasTimestampIsoNoninclusive = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.page.Page_creation_report.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.page.Page_creation_report.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.page.Page_creation_report} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.page.Page_creation_report.toObject = function(includeInstance, msg) {
  var f, obj = {
    success: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    newPidBis: jspb.Message.getFieldWithDefault(msg, 2, ""),
    newApparentPageName: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.page.Page_creation_report}
 */
proto.apiv4.page.Page_creation_report.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.page.Page_creation_report;
  return proto.apiv4.page.Page_creation_report.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.page.Page_creation_report} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.page.Page_creation_report}
 */
proto.apiv4.page.Page_creation_report.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNewPidBis(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setNewApparentPageName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.page.Page_creation_report.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.page.Page_creation_report.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.page.Page_creation_report} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.page.Page_creation_report.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getNewPidBis();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getNewApparentPageName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional bool success = 1;
 * @return {boolean}
 */
proto.apiv4.page.Page_creation_report.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.apiv4.page.Page_creation_report.prototype.setSuccess = function(value) {
  jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string new_pid_bis = 2;
 * @return {string}
 */
proto.apiv4.page.Page_creation_report.prototype.getNewPidBis = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.apiv4.page.Page_creation_report.prototype.setNewPidBis = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string new_apparent_page_name = 3;
 * @return {string}
 */
proto.apiv4.page.Page_creation_report.prototype.getNewApparentPageName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.apiv4.page.Page_creation_report.prototype.setNewApparentPageName = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


goog.object.extend(exports, proto.apiv4.page);
