/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var include_user_pb = require('../include/user_pb.js');
goog.object.extend(proto, include_user_pb);
goog.exportSymbol('proto.apiv4.revision.Revision_metadata', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.revision.Revision_metadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apiv4.revision.Revision_metadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.revision.Revision_metadata.displayName = 'proto.apiv4.revision.Revision_metadata';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.revision.Revision_metadata.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.revision.Revision_metadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.revision.Revision_metadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.revision.Revision_metadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    revIdBis: jspb.Message.getFieldWithDefault(msg, 1, ""),
    creator: (f = msg.getCreator()) && include_user_pb.User_public_model.toObject(includeInstance, f),
    creationTimeBis: jspb.Message.getFieldWithDefault(msg, 3, ""),
    comment: jspb.Message.getFieldWithDefault(msg, 4, ""),
    relatedPageIdBis: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.revision.Revision_metadata}
 */
proto.apiv4.revision.Revision_metadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.revision.Revision_metadata;
  return proto.apiv4.revision.Revision_metadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.revision.Revision_metadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.revision.Revision_metadata}
 */
proto.apiv4.revision.Revision_metadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRevIdBis(value);
      break;
    case 2:
      var value = new include_user_pb.User_public_model;
      reader.readMessage(value,include_user_pb.User_public_model.deserializeBinaryFromReader);
      msg.setCreator(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreationTimeBis(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setComment(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setRelatedPageIdBis(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.revision.Revision_metadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.revision.Revision_metadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.revision.Revision_metadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.revision.Revision_metadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRevIdBis();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCreator();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      include_user_pb.User_public_model.serializeBinaryToWriter
    );
  }
  f = message.getCreationTimeBis();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getComment();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getRelatedPageIdBis();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string rev_id_bis = 1;
 * @return {string}
 */
proto.apiv4.revision.Revision_metadata.prototype.getRevIdBis = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.apiv4.revision.Revision_metadata.prototype.setRevIdBis = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional apiv4.user.User_public_model creator = 2;
 * @return {?proto.apiv4.user.User_public_model}
 */
proto.apiv4.revision.Revision_metadata.prototype.getCreator = function() {
  return /** @type{?proto.apiv4.user.User_public_model} */ (
    jspb.Message.getWrapperField(this, include_user_pb.User_public_model, 2));
};


/** @param {?proto.apiv4.user.User_public_model|undefined} value */
proto.apiv4.revision.Revision_metadata.prototype.setCreator = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.apiv4.revision.Revision_metadata.prototype.clearCreator = function() {
  this.setCreator(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apiv4.revision.Revision_metadata.prototype.hasCreator = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string creation_time_bis = 3;
 * @return {string}
 */
proto.apiv4.revision.Revision_metadata.prototype.getCreationTimeBis = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.apiv4.revision.Revision_metadata.prototype.setCreationTimeBis = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string comment = 4;
 * @return {string}
 */
proto.apiv4.revision.Revision_metadata.prototype.getComment = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.apiv4.revision.Revision_metadata.prototype.setComment = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string related_page_id_bis = 5;
 * @return {string}
 */
proto.apiv4.revision.Revision_metadata.prototype.getRelatedPageIdBis = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.apiv4.revision.Revision_metadata.prototype.setRelatedPageIdBis = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


goog.object.extend(exports, proto.apiv4.revision);
