/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var include_support_pb = require('../include/support_pb.js');
goog.object.extend(proto, include_support_pb);
goog.exportSymbol('proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code', null, global);
goog.exportSymbol('proto.apiv4.user.Obtain_credential_by_password_naive_attempt', null, global);
goog.exportSymbol('proto.apiv4.user.Obtain_credential_by_password_pow_1', null, global);
goog.exportSymbol('proto.apiv4.user.Obtain_credential_mail_otp_step_0_response', null, global);
goog.exportSymbol('proto.apiv4.user.Obtain_credential_mail_otp_step_1_response', null, global);
goog.exportSymbol('proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential', null, global);
goog.exportSymbol('proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr', null, global);
goog.exportSymbol('proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent', null, global);
goog.exportSymbol('proto.apiv4.user.Require_credential_expiry', null, global);
goog.exportSymbol('proto.apiv4.user.Response_credential_granted', null, global);
goog.exportSymbol('proto.apiv4.user.User_private_model', null, global);
goog.exportSymbol('proto.apiv4.user.User_public_model', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.user.User_public_model = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.apiv4.user.User_public_model.repeatedFields_, null);
};
goog.inherits(proto.apiv4.user.User_public_model, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.user.User_public_model.displayName = 'proto.apiv4.user.User_public_model';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.user.User_private_model = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.apiv4.user.User_private_model.repeatedFields_, null);
};
goog.inherits(proto.apiv4.user.User_private_model, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.user.User_private_model.displayName = 'proto.apiv4.user.User_private_model';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.apiv4.user.Obtain_credential_by_password_naive_attempt.oneofGroups_);
};
goog.inherits(proto.apiv4.user.Obtain_credential_by_password_naive_attempt, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.user.Obtain_credential_by_password_naive_attempt.displayName = 'proto.apiv4.user.Obtain_credential_by_password_naive_attempt';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.apiv4.user.Obtain_credential_by_password_pow_1.oneofGroups_);
};
goog.inherits(proto.apiv4.user.Obtain_credential_by_password_pow_1, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.user.Obtain_credential_by_password_pow_1.displayName = 'proto.apiv4.user.Obtain_credential_by_password_pow_1';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential.displayName = 'proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code.displayName = 'proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.displayName = 'proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_0_response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apiv4.user.Obtain_credential_mail_otp_step_0_response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.user.Obtain_credential_mail_otp_step_0_response.displayName = 'proto.apiv4.user.Obtain_credential_mail_otp_step_0_response';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent.displayName = 'proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_1_response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apiv4.user.Obtain_credential_mail_otp_step_1_response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.user.Obtain_credential_mail_otp_step_1_response.displayName = 'proto.apiv4.user.Obtain_credential_mail_otp_step_1_response';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apiv4.user.Response_credential_granted = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apiv4.user.Response_credential_granted, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apiv4.user.Response_credential_granted.displayName = 'proto.apiv4.user.Response_credential_granted';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.apiv4.user.User_public_model.repeatedFields_ = [5,6,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.user.User_public_model.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.user.User_public_model.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.user.User_public_model} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.User_public_model.toObject = function(includeInstance, msg) {
  var f, obj = {
    userIdBis: jspb.Message.getFieldWithDefault(msg, 1, ""),
    userCreationTimeIso: jspb.Message.getFieldWithDefault(msg, 2, ""),
    userName: jspb.Message.getFieldWithDefault(msg, 3, ""),
    userNickName: jspb.Message.getFieldWithDefault(msg, 4, ""),
    userGroupsList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    userTagsList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f,
    userActivitiesList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.user.User_public_model}
 */
proto.apiv4.user.User_public_model.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.user.User_public_model;
  return proto.apiv4.user.User_public_model.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.user.User_public_model} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.user.User_public_model}
 */
proto.apiv4.user.User_public_model.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserIdBis(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserCreationTimeIso(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserNickName(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addUserGroups(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addUserTags(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addUserActivities(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.user.User_public_model.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.user.User_public_model.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.user.User_public_model} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.User_public_model.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserIdBis();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUserCreationTimeIso();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUserName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getUserNickName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getUserGroupsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = message.getUserTagsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
  f = message.getUserActivitiesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
};


/**
 * optional string user_id_bis = 1;
 * @return {string}
 */
proto.apiv4.user.User_public_model.prototype.getUserIdBis = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.apiv4.user.User_public_model.prototype.setUserIdBis = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string user_creation_time_iso = 2;
 * @return {string}
 */
proto.apiv4.user.User_public_model.prototype.getUserCreationTimeIso = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.apiv4.user.User_public_model.prototype.setUserCreationTimeIso = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string user_name = 3;
 * @return {string}
 */
proto.apiv4.user.User_public_model.prototype.getUserName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.apiv4.user.User_public_model.prototype.setUserName = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string user_nick_name = 4;
 * @return {string}
 */
proto.apiv4.user.User_public_model.prototype.getUserNickName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.apiv4.user.User_public_model.prototype.setUserNickName = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated string user_groups = 5;
 * @return {!Array<string>}
 */
proto.apiv4.user.User_public_model.prototype.getUserGroupsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/** @param {!Array<string>} value */
proto.apiv4.user.User_public_model.prototype.setUserGroupsList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.apiv4.user.User_public_model.prototype.addUserGroups = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.apiv4.user.User_public_model.prototype.clearUserGroupsList = function() {
  this.setUserGroupsList([]);
};


/**
 * repeated string user_tags = 6;
 * @return {!Array<string>}
 */
proto.apiv4.user.User_public_model.prototype.getUserTagsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};


/** @param {!Array<string>} value */
proto.apiv4.user.User_public_model.prototype.setUserTagsList = function(value) {
  jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.apiv4.user.User_public_model.prototype.addUserTags = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.apiv4.user.User_public_model.prototype.clearUserTagsList = function() {
  this.setUserTagsList([]);
};


/**
 * repeated string user_activities = 7;
 * @return {!Array<string>}
 */
proto.apiv4.user.User_public_model.prototype.getUserActivitiesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/** @param {!Array<string>} value */
proto.apiv4.user.User_public_model.prototype.setUserActivitiesList = function(value) {
  jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.apiv4.user.User_public_model.prototype.addUserActivities = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.apiv4.user.User_public_model.prototype.clearUserActivitiesList = function() {
  this.setUserActivitiesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.apiv4.user.User_private_model.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.user.User_private_model.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.user.User_private_model.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.user.User_private_model} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.User_private_model.toObject = function(includeInstance, msg) {
  var f, obj = {
    userPublicModel: (f = msg.getUserPublicModel()) && proto.apiv4.user.User_public_model.toObject(includeInstance, f),
    email: jspb.Message.getFieldWithDefault(msg, 2, ""),
    emailVerified: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    lastPasswordUpdateIso: jspb.Message.getFieldWithDefault(msg, 4, ""),
    bookmarksList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.user.User_private_model}
 */
proto.apiv4.user.User_private_model.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.user.User_private_model;
  return proto.apiv4.user.User_private_model.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.user.User_private_model} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.user.User_private_model}
 */
proto.apiv4.user.User_private_model.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.apiv4.user.User_public_model;
      reader.readMessage(value,proto.apiv4.user.User_public_model.deserializeBinaryFromReader);
      msg.setUserPublicModel(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEmailVerified(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastPasswordUpdateIso(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addBookmarks(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.user.User_private_model.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.user.User_private_model.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.user.User_private_model} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.User_private_model.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserPublicModel();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.apiv4.user.User_public_model.serializeBinaryToWriter
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEmailVerified();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getLastPasswordUpdateIso();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getBookmarksList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
};


/**
 * optional User_public_model user_public_model = 1;
 * @return {?proto.apiv4.user.User_public_model}
 */
proto.apiv4.user.User_private_model.prototype.getUserPublicModel = function() {
  return /** @type{?proto.apiv4.user.User_public_model} */ (
    jspb.Message.getWrapperField(this, proto.apiv4.user.User_public_model, 1));
};


/** @param {?proto.apiv4.user.User_public_model|undefined} value */
proto.apiv4.user.User_private_model.prototype.setUserPublicModel = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.apiv4.user.User_private_model.prototype.clearUserPublicModel = function() {
  this.setUserPublicModel(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apiv4.user.User_private_model.prototype.hasUserPublicModel = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string email = 2;
 * @return {string}
 */
proto.apiv4.user.User_private_model.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.apiv4.user.User_private_model.prototype.setEmail = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool email_verified = 3;
 * @return {boolean}
 */
proto.apiv4.user.User_private_model.prototype.getEmailVerified = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.apiv4.user.User_private_model.prototype.setEmailVerified = function(value) {
  jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional string last_password_update_iso = 4;
 * @return {string}
 */
proto.apiv4.user.User_private_model.prototype.getLastPasswordUpdateIso = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.apiv4.user.User_private_model.prototype.setLastPasswordUpdateIso = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated string bookmarks = 5;
 * @return {!Array<string>}
 */
proto.apiv4.user.User_private_model.prototype.getBookmarksList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/** @param {!Array<string>} value */
proto.apiv4.user.User_private_model.prototype.setBookmarksList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.apiv4.user.User_private_model.prototype.addBookmarks = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.apiv4.user.User_private_model.prototype.clearBookmarksList = function() {
  this.setBookmarksList([]);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.UserIdentificationCase = {
  USER_IDENTIFICATION_NOT_SET: 0,
  USER_NAME_NORMALIZED: 1,
  USER_EMAIL_PRIMARY: 2
};

/**
 * @return {proto.apiv4.user.Obtain_credential_by_password_naive_attempt.UserIdentificationCase}
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.prototype.getUserIdentificationCase = function() {
  return /** @type {proto.apiv4.user.Obtain_credential_by_password_naive_attempt.UserIdentificationCase} */(jspb.Message.computeOneofCase(this, proto.apiv4.user.Obtain_credential_by_password_naive_attempt.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.user.Obtain_credential_by_password_naive_attempt.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.user.Obtain_credential_by_password_naive_attempt} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.toObject = function(includeInstance, msg) {
  var f, obj = {
    userNameNormalized: jspb.Message.getFieldWithDefault(msg, 1, ""),
    userEmailPrimary: jspb.Message.getFieldWithDefault(msg, 2, ""),
    password: jspb.Message.getFieldWithDefault(msg, 3, ""),
    requireExpiry: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.user.Obtain_credential_by_password_naive_attempt}
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.user.Obtain_credential_by_password_naive_attempt;
  return proto.apiv4.user.Obtain_credential_by_password_naive_attempt.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.user.Obtain_credential_by_password_naive_attempt} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.user.Obtain_credential_by_password_naive_attempt}
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserNameNormalized(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserEmailPrimary(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    case 4:
      var value = /** @type {!proto.apiv4.user.Require_credential_expiry} */ (reader.readEnum());
      msg.setRequireExpiry(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.user.Obtain_credential_by_password_naive_attempt.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.user.Obtain_credential_by_password_naive_attempt} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRequireExpiry();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
};


/**
 * optional string user_name_normalized = 1;
 * @return {string}
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.prototype.getUserNameNormalized = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.prototype.setUserNameNormalized = function(value) {
  jspb.Message.setOneofField(this, 1, proto.apiv4.user.Obtain_credential_by_password_naive_attempt.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.prototype.clearUserNameNormalized = function() {
  jspb.Message.setOneofField(this, 1, proto.apiv4.user.Obtain_credential_by_password_naive_attempt.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.prototype.hasUserNameNormalized = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string user_email_primary = 2;
 * @return {string}
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.prototype.getUserEmailPrimary = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.prototype.setUserEmailPrimary = function(value) {
  jspb.Message.setOneofField(this, 2, proto.apiv4.user.Obtain_credential_by_password_naive_attempt.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.prototype.clearUserEmailPrimary = function() {
  jspb.Message.setOneofField(this, 2, proto.apiv4.user.Obtain_credential_by_password_naive_attempt.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.prototype.hasUserEmailPrimary = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string password = 3;
 * @return {string}
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.prototype.setPassword = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Require_credential_expiry require_expiry = 4;
 * @return {!proto.apiv4.user.Require_credential_expiry}
 */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.prototype.getRequireExpiry = function() {
  return /** @type {!proto.apiv4.user.Require_credential_expiry} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.apiv4.user.Require_credential_expiry} value */
proto.apiv4.user.Obtain_credential_by_password_naive_attempt.prototype.setRequireExpiry = function(value) {
  jspb.Message.setProto3EnumField(this, 4, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.UserIdentificationCase = {
  USER_IDENTIFICATION_NOT_SET: 0,
  USER_NAME_NORMALIZED: 1,
  USER_EMAIL_PRIMARY: 2
};

/**
 * @return {proto.apiv4.user.Obtain_credential_by_password_pow_1.UserIdentificationCase}
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.getUserIdentificationCase = function() {
  return /** @type {proto.apiv4.user.Obtain_credential_by_password_pow_1.UserIdentificationCase} */(jspb.Message.computeOneofCase(this, proto.apiv4.user.Obtain_credential_by_password_pow_1.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.user.Obtain_credential_by_password_pow_1.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.user.Obtain_credential_by_password_pow_1} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.toObject = function(includeInstance, msg) {
  var f, obj = {
    userNameNormalized: jspb.Message.getFieldWithDefault(msg, 1, ""),
    userEmailPrimary: jspb.Message.getFieldWithDefault(msg, 2, ""),
    password: jspb.Message.getFieldWithDefault(msg, 3, ""),
    requireExpiry: jspb.Message.getFieldWithDefault(msg, 4, 0),
    powProduct: (f = msg.getPowProduct()) && include_support_pb.Proof_of_work_produced.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.user.Obtain_credential_by_password_pow_1}
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.user.Obtain_credential_by_password_pow_1;
  return proto.apiv4.user.Obtain_credential_by_password_pow_1.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.user.Obtain_credential_by_password_pow_1} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.user.Obtain_credential_by_password_pow_1}
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserNameNormalized(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserEmailPrimary(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    case 4:
      var value = /** @type {!proto.apiv4.user.Require_credential_expiry} */ (reader.readEnum());
      msg.setRequireExpiry(value);
      break;
    case 5:
      var value = new include_support_pb.Proof_of_work_produced;
      reader.readMessage(value,include_support_pb.Proof_of_work_produced.deserializeBinaryFromReader);
      msg.setPowProduct(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.user.Obtain_credential_by_password_pow_1.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.user.Obtain_credential_by_password_pow_1} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRequireExpiry();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getPowProduct();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      include_support_pb.Proof_of_work_produced.serializeBinaryToWriter
    );
  }
};


/**
 * optional string user_name_normalized = 1;
 * @return {string}
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.getUserNameNormalized = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.setUserNameNormalized = function(value) {
  jspb.Message.setOneofField(this, 1, proto.apiv4.user.Obtain_credential_by_password_pow_1.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.clearUserNameNormalized = function() {
  jspb.Message.setOneofField(this, 1, proto.apiv4.user.Obtain_credential_by_password_pow_1.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.hasUserNameNormalized = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string user_email_primary = 2;
 * @return {string}
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.getUserEmailPrimary = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.setUserEmailPrimary = function(value) {
  jspb.Message.setOneofField(this, 2, proto.apiv4.user.Obtain_credential_by_password_pow_1.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.clearUserEmailPrimary = function() {
  jspb.Message.setOneofField(this, 2, proto.apiv4.user.Obtain_credential_by_password_pow_1.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.hasUserEmailPrimary = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string password = 3;
 * @return {string}
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.setPassword = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Require_credential_expiry require_expiry = 4;
 * @return {!proto.apiv4.user.Require_credential_expiry}
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.getRequireExpiry = function() {
  return /** @type {!proto.apiv4.user.Require_credential_expiry} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.apiv4.user.Require_credential_expiry} value */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.setRequireExpiry = function(value) {
  jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional apiv4.support.Proof_of_work_produced pow_product = 5;
 * @return {?proto.apiv4.support.Proof_of_work_produced}
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.getPowProduct = function() {
  return /** @type{?proto.apiv4.support.Proof_of_work_produced} */ (
    jspb.Message.getWrapperField(this, include_support_pb.Proof_of_work_produced, 5));
};


/** @param {?proto.apiv4.support.Proof_of_work_produced|undefined} value */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.setPowProduct = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.clearPowProduct = function() {
  this.setPowProduct(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apiv4.user.Obtain_credential_by_password_pow_1.prototype.hasPowProduct = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential.toObject = function(includeInstance, msg) {
  var f, obj = {
    targetUidBis: jspb.Message.getFieldWithDefault(msg, 1, ""),
    intermediateAccessGrantToken: jspb.Message.getFieldWithDefault(msg, 2, ""),
    expiryIso: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential}
 */
proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential;
  return proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential}
 */
proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTargetUidBis(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setIntermediateAccessGrantToken(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setExpiryIso(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTargetUidBis();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIntermediateAccessGrantToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getExpiryIso();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string target_uid_bis = 1;
 * @return {string}
 */
proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential.prototype.getTargetUidBis = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential.prototype.setTargetUidBis = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string intermediate_access_grant_token = 2;
 * @return {string}
 */
proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential.prototype.getIntermediateAccessGrantToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential.prototype.setIntermediateAccessGrantToken = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string expiry_iso = 3;
 * @return {string}
 */
proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential.prototype.getExpiryIso = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.apiv4.user.Reply_2fa_hmac_totp_required_to_obtain_credential.prototype.setExpiryIso = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code.toObject = function(includeInstance, msg) {
  var f, obj = {
    targetUidBis: jspb.Message.getFieldWithDefault(msg, 1, ""),
    intermediateAccessGrantToken: jspb.Message.getFieldWithDefault(msg, 2, ""),
    totpToken: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code}
 */
proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code;
  return proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code}
 */
proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTargetUidBis(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setIntermediateAccessGrantToken(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTotpToken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTargetUidBis();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIntermediateAccessGrantToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTotpToken();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string target_uid_bis = 1;
 * @return {string}
 */
proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code.prototype.getTargetUidBis = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code.prototype.setTargetUidBis = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string intermediate_access_grant_token = 2;
 * @return {string}
 */
proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code.prototype.getIntermediateAccessGrantToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code.prototype.setIntermediateAccessGrantToken = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string totp_token = 3;
 * @return {string}
 */
proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code.prototype.getTotpToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.apiv4.user.Obtain_credential_2fa_hmac_totp_code.prototype.setTotpToken = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.toObject = function(includeInstance, msg) {
  var f, obj = {
    targetUidBis: jspb.Message.getFieldWithDefault(msg, 1, ""),
    intermediateAccessGrantToken: jspb.Message.getFieldWithDefault(msg, 2, ""),
    emailHint: jspb.Message.getFieldWithDefault(msg, 3, ""),
    expiryIso: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr}
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr;
  return proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr}
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTargetUidBis(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setIntermediateAccessGrantToken(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmailHint(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setExpiryIso(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTargetUidBis();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIntermediateAccessGrantToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEmailHint();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getExpiryIso();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string target_uid_bis = 1;
 * @return {string}
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.prototype.getTargetUidBis = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.prototype.setTargetUidBis = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string intermediate_access_grant_token = 2;
 * @return {string}
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.prototype.getIntermediateAccessGrantToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.prototype.setIntermediateAccessGrantToken = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string email_hint = 3;
 * @return {string}
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.prototype.getEmailHint = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.prototype.setEmailHint = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string expiry_iso = 4;
 * @return {string}
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.prototype.getExpiryIso = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.apiv4.user.Reply_2fa_mail_otp_step_0_verify_email_addr.prototype.setExpiryIso = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_0_response.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.user.Obtain_credential_mail_otp_step_0_response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.user.Obtain_credential_mail_otp_step_0_response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_0_response.toObject = function(includeInstance, msg) {
  var f, obj = {
    targetUidBis: jspb.Message.getFieldWithDefault(msg, 1, ""),
    intermediateAccessGrantToken: jspb.Message.getFieldWithDefault(msg, 2, ""),
    fullEmail: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.user.Obtain_credential_mail_otp_step_0_response}
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_0_response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.user.Obtain_credential_mail_otp_step_0_response;
  return proto.apiv4.user.Obtain_credential_mail_otp_step_0_response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.user.Obtain_credential_mail_otp_step_0_response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.user.Obtain_credential_mail_otp_step_0_response}
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_0_response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTargetUidBis(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setIntermediateAccessGrantToken(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFullEmail(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_0_response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.user.Obtain_credential_mail_otp_step_0_response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.user.Obtain_credential_mail_otp_step_0_response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_0_response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTargetUidBis();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIntermediateAccessGrantToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFullEmail();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string target_uid_bis = 1;
 * @return {string}
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_0_response.prototype.getTargetUidBis = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.apiv4.user.Obtain_credential_mail_otp_step_0_response.prototype.setTargetUidBis = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string intermediate_access_grant_token = 2;
 * @return {string}
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_0_response.prototype.getIntermediateAccessGrantToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.apiv4.user.Obtain_credential_mail_otp_step_0_response.prototype.setIntermediateAccessGrantToken = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string full_email = 3;
 * @return {string}
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_0_response.prototype.getFullEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.apiv4.user.Obtain_credential_mail_otp_step_0_response.prototype.setFullEmail = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent.toObject = function(includeInstance, msg) {
  var f, obj = {
    expiryIso: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent}
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent;
  return proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent}
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setExpiryIso(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getExpiryIso();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string expiry_iso = 1;
 * @return {string}
 */
proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent.prototype.getExpiryIso = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.apiv4.user.Reply_2fa_mail_otp_step_1_mail_sent.prototype.setExpiryIso = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_1_response.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.user.Obtain_credential_mail_otp_step_1_response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.user.Obtain_credential_mail_otp_step_1_response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_1_response.toObject = function(includeInstance, msg) {
  var f, obj = {
    targetUidBis: jspb.Message.getFieldWithDefault(msg, 1, ""),
    intermediateAccessGrantToken: jspb.Message.getFieldWithDefault(msg, 2, ""),
    mailToken: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.user.Obtain_credential_mail_otp_step_1_response}
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_1_response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.user.Obtain_credential_mail_otp_step_1_response;
  return proto.apiv4.user.Obtain_credential_mail_otp_step_1_response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.user.Obtain_credential_mail_otp_step_1_response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.user.Obtain_credential_mail_otp_step_1_response}
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_1_response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTargetUidBis(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setIntermediateAccessGrantToken(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMailToken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_1_response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.user.Obtain_credential_mail_otp_step_1_response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.user.Obtain_credential_mail_otp_step_1_response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_1_response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTargetUidBis();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIntermediateAccessGrantToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMailToken();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string target_uid_bis = 1;
 * @return {string}
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_1_response.prototype.getTargetUidBis = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.apiv4.user.Obtain_credential_mail_otp_step_1_response.prototype.setTargetUidBis = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string intermediate_access_grant_token = 2;
 * @return {string}
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_1_response.prototype.getIntermediateAccessGrantToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.apiv4.user.Obtain_credential_mail_otp_step_1_response.prototype.setIntermediateAccessGrantToken = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string mail_token = 3;
 * @return {string}
 */
proto.apiv4.user.Obtain_credential_mail_otp_step_1_response.prototype.getMailToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.apiv4.user.Obtain_credential_mail_otp_step_1_response.prototype.setMailToken = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apiv4.user.Response_credential_granted.prototype.toObject = function(opt_includeInstance) {
  return proto.apiv4.user.Response_credential_granted.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apiv4.user.Response_credential_granted} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Response_credential_granted.toObject = function(includeInstance, msg) {
  var f, obj = {
    credential: (f = msg.getCredential()) && include_support_pb.Credential.toObject(includeInstance, f),
    expiryIso: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apiv4.user.Response_credential_granted}
 */
proto.apiv4.user.Response_credential_granted.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apiv4.user.Response_credential_granted;
  return proto.apiv4.user.Response_credential_granted.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apiv4.user.Response_credential_granted} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apiv4.user.Response_credential_granted}
 */
proto.apiv4.user.Response_credential_granted.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new include_support_pb.Credential;
      reader.readMessage(value,include_support_pb.Credential.deserializeBinaryFromReader);
      msg.setCredential(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setExpiryIso(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apiv4.user.Response_credential_granted.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apiv4.user.Response_credential_granted.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apiv4.user.Response_credential_granted} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apiv4.user.Response_credential_granted.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCredential();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      include_support_pb.Credential.serializeBinaryToWriter
    );
  }
  f = message.getExpiryIso();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional apiv4.support.Credential credential = 1;
 * @return {?proto.apiv4.support.Credential}
 */
proto.apiv4.user.Response_credential_granted.prototype.getCredential = function() {
  return /** @type{?proto.apiv4.support.Credential} */ (
    jspb.Message.getWrapperField(this, include_support_pb.Credential, 1));
};


/** @param {?proto.apiv4.support.Credential|undefined} value */
proto.apiv4.user.Response_credential_granted.prototype.setCredential = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.apiv4.user.Response_credential_granted.prototype.clearCredential = function() {
  this.setCredential(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apiv4.user.Response_credential_granted.prototype.hasCredential = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string expiry_iso = 2;
 * @return {string}
 */
proto.apiv4.user.Response_credential_granted.prototype.getExpiryIso = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.apiv4.user.Response_credential_granted.prototype.setExpiryIso = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.apiv4.user.Require_credential_expiry = {
  EXPIRY_TYPE_ONE_DAY: 0,
  EXPIRY_TYPE_90_DAYS: 1
};

goog.object.extend(exports, proto.apiv4.user);
